"""
feature_adapter.py — Telemetry to Model-Specific Feature Transformation Adapter
================================================================================
Battery Digital Twin | Models Layer

Architecture:
  Digital Twin
        ↓
  Virtual Sensors
        ↓
  Virtual BMS
        ↓
  Telemetry JSON
        ↓
  Feature Adapter (feature_adapter.py)
        ↓
  Trained ML Models (soc_model.pkl, soh_model.pkl, rul_model.pkl, anomaly_model.pkl)
        ↓
  Predictions

Responsibility:
  - Inspects required feature schemas for each model
  - Transforms BMS telemetry JSON packets into model-specific feature vectors
  - Clearly reports missing features if required inputs cannot be generated by Digital Twin
  - Does NOT fabricate missing features silently
"""

from typing import Dict, Any, List, Tuple

# Standard Feature Schemas for expected ML models
MODEL_FEATURE_SCHEMAS = {
    'soc_model.pkl': [
        'pack_voltage_V', 'pack_current_A', 'pack_temp_avg_C',
        'cell_voltage_mean', 'cell_voltage_min', 'cell_voltage_max', 'cell_delta_V'
    ],
    'soh_model.pkl': [
        'cycle_count', 'pack_voltage_V', 'pack_temp_max_C',
        'cell_voltage_mean', 'cell_voltage_std', 'cell_temp_mean', 'effective_resistance_mean'
    ],
    'rul_model.pkl': [
        'cycle_count', 'soh_percent', 'pack_temp_avg_C',
        'cell_delta_V', 'cell_temp_max'
    ],
    'anomaly_model.pkl': [
        'pack_voltage_V', 'pack_current_A', 'cell_delta_V',
        'cell_temp_max', 'cooling_flow', 'fault_count', 'contactor_closed'
    ]
}


def _calculate_std(values: List[float]) -> float:
    """Compute sample standard deviation."""
    if len(values) < 2:
        return 0.0
    mean = sum(values) / len(values)
    var = sum((x - mean) ** 2 for x in values) / len(values)
    return var ** 0.5


def extract_base_telemetry_features(telemetry_packet: dict) -> Tuple[dict, List[str]]:
    """
    Extract raw feature dictionary and track any missing telemetry fields.

    Args:
        telemetry_packet: BMS JSON packet from telemetry_generator.py

    Returns:
        (feature_dict, missing_fields_list)
    """
    missing_fields = []
    features = {}

    # Extract pack level
    pack = telemetry_packet.get('pack', {})
    features['pack_voltage_V']   = pack.get('voltage_V', telemetry_packet.get('pack_voltage_V'))
    features['pack_current_A']   = pack.get('current_A', telemetry_packet.get('pack_current_A'))
    features['power_W']          = pack.get('power_W', round(features['pack_voltage_V'] * features['pack_current_A'], 2) if features['pack_voltage_V'] is not None and features['pack_current_A'] is not None else None)
    features['cycle_count']      = pack.get('cycle_count', telemetry_packet.get('cycle_count'))
    features['pack_soc_percent'] = pack.get('soc_percent', telemetry_packet.get('pack_soc_percent'))

    # Extract cell statistics
    cells = telemetry_packet.get('cells', [])
    if cells:
        voltages = [c.get('voltage_V', 0.0) for c in cells if 'voltage_V' in c]
        temps    = [c.get('temperature_C', 0.0) for c in cells if 'temperature_C' in c]
        r_effs   = [c.get('effective_resistance_ohm', 0.020) for c in cells if 'effective_resistance_ohm' in c]

        features['cell_voltage_mean'] = sum(voltages) / len(voltages) if voltages else 0.0
        features['cell_voltage_min']  = min(voltages) if voltages else 0.0
        features['cell_voltage_max']  = max(voltages) if voltages else 0.0
        features['cell_voltage_std']  = _calculate_std(voltages)
        features['cell_delta_V']      = telemetry_packet.get('cell_delta_V', (max(voltages) - min(voltages)) if voltages else 0.0)

        features['cell_temp_mean']    = sum(temps) / len(temps) if temps else 0.0
        features['cell_temp_max']     = max(temps) if temps else 0.0
        features['cell_temp_std']     = _calculate_std(temps)

        features['effective_resistance_mean'] = sum(r_effs) / len(r_effs) if r_effs else 0.0
    else:
        missing_fields.append('cells_array')

    # Thermal system
    thermal = telemetry_packet.get('thermal_system', {})
    features['cooling_flow']      = thermal.get('coolant_flow', telemetry_packet.get('cooling_status', {}).get('flow_lpm', 0.0))
    features['pack_temp_max_C']   = thermal.get('max_temperature_C', telemetry_packet.get('pack_temp_max_C', 0.0))
    features['pack_temp_avg_C']   = thermal.get('avg_temperature_C', telemetry_packet.get('pack_temp_avg_C', 0.0))

    # BMS protection status
    bms = telemetry_packet.get('bms_status', {})
    features['fault_count']       = bms.get('warning_count', telemetry_packet.get('fault_count', 0))
    contactor_str                 = bms.get('contactor_state', telemetry_packet.get('contactor', 'CLOSED'))
    features['contactor_closed']  = 1 if contactor_str == 'CLOSED' else 0

    # Verify if any critical feature was None
    for k, v in features.items():
        if v is None:
            missing_fields.append(k)

    return features, missing_fields


def transform_telemetry_for_model(telemetry_packet: dict, model_filename: str) -> Dict[str, Any]:
    """
    Transform telemetry packet into model-specific feature vector according to required schema.

    Args:
        telemetry_packet: BMS JSON packet
        model_filename:   Name of target model file (e.g. 'soc_model.pkl')

    Returns:
        dict with:
          'status': 'SUCCESS' | 'MISSING_FEATURES'
          'model': model_filename
          'feature_schema': [...]
          'feature_vector': [...]
          'missing_features': [...]
    """
    schema = MODEL_FEATURE_SCHEMAS.get(model_filename, [])
    if not schema:
        # Default fallback to all extracted base features
        base_features, missing = extract_base_telemetry_features(telemetry_packet)
        return {
            'status': 'SUCCESS' if not missing else 'MISSING_FEATURES',
            'model': model_filename,
            'feature_schema': list(base_features.keys()),
            'feature_vector': list(base_features.values()),
            'feature_dict': base_features,
            'missing_features': missing
        }

    base_features, _ = extract_base_telemetry_features(telemetry_packet)
    vector = []
    missing_for_model = []

    for req_feature in schema:
        if req_feature in base_features and base_features[req_feature] is not None:
            vector.append(base_features[req_feature])
        else:
            missing_for_model.append(req_feature)
            vector.append(None)

    if missing_for_model:
        return {
            'status': 'MISSING_FEATURES',
            'model': model_filename,
            'feature_schema': schema,
            'feature_vector': None,
            'missing_features': missing_for_model,
            'error_message': f'Digital Twin cannot generate required feature(s): {missing_for_model}'
        }

    return {
        'status': 'SUCCESS',
        'model': model_filename,
        'feature_schema': schema,
        'feature_vector': vector,
        'feature_dict': {k: v for k, v in zip(schema, vector)},
        'missing_features': []
    }


# ── Standalone Test ───────────────────────────────────────────────────────────
if __name__ == '__main__':
    print("=" * 60)
    print("  Feature Adapter — Standalone Test")
    print("=" * 60)

    mock_packet = {
        'timestamp': '2026-08-30T23:00:00Z',
        'pack': {'voltage_V': 30.24, 'current_A': 15.0, 'power_W': 453.6, 'cycle_count': 100},
        'cells': [{'id': i, 'voltage_V': 3.78, 'temperature_C': 30.0, 'effective_resistance_ohm': 0.020} for i in range(1, 9)],
        'thermal_system': {'coolant_flow': 8.5, 'max_temperature_C': 34.0, 'avg_temperature_C': 30.0},
        'bms_status': {'warning_count': 0, 'contactor_state': 'CLOSED'}
    }

    for model_file in MODEL_FEATURE_SCHEMAS:
        transformed = transform_telemetry_for_model(mock_packet, model_file)
        print(f"\nModel Target: {model_file}")
        print(f"  Status       : {transformed['status']}")
        print(f"  Schema Length: {len(transformed['feature_schema'])}")
        print(f"  Vector       : {transformed['feature_vector']}")
    print()
